### ISSUE TITLE
Dockerfile for Valhalla

### ISSUE THREAD

**Issue by tomtaylor** [valhalla/chef-valhalla#62]
Hello, I wanted to play around with Valhalla, and ended up porting the bash script to a Dockerfile. It assumes you have each of the Valhalla components in subdirectories below the Dockerfile. You probably want to change the OSM export files for your own testing. 

I'm not expecting this to replace the chef repo, but it might be useful for someone, so I thought I'd drop it in here. If it's useful to put this into a separate repo, let me know.

https://gist.github.com/tomtaylor/b84e05a3aaeb337e4e75

**Comment by kevinkreiser** [comment]
Thanks much for doing this! I agree this is totally useful! I haven't played with docker myself but from what I understand it seems really handy.

We'll have to figure out the right place to put this but I definitely think we should share it with others so that if their deployment could make use of it they'd have a head start.

We'll leave the issue open until we find a home for it under the valhalla github org. Any suggestions? Where might docker enthusiasts usually keep their `dockerfile`? A separate repo?

**Comment by tomtaylor** [comment]
I think it could probably sit in a separate repo, with a bootstrap script that clones each of the required valhalla repositories into subdirectories. That's how I've got it set up, and it works pretty nicely.

**Comment by tomtaylor** [comment]
Here's a first cut of that. Let me know if you'd like to take over the repo.

https://github.com/tomtaylor/valhalla-docker

**Comment by kevinkreiser** [comment]
Thanks! We can take a copy of it into the valhalla org. It would be great if we could keep this up-to-date as we make changes to various bits for whoever's making use of it. What might be the best way to do that? Is there any way to run dockerfiles using CI's like travis or circleci?

**Comment by kevinkreiser** [comment]
I've forked the repo so its visible within the valhalla org, does this seem sufficient to everyone?

**Comment by tomtaylor** [comment]
I've not tried it, but this suggests it's possible to run Docker in Travis CI: https://github.com/moul/travis-docker

The repo itself won't change as the components change, so you might want to consider another way of triggering new builds.

**Comment by kevinkreiser** [comment]
Yeah I was just thinking as the process changes but indeed it may be the case that the process is the same but stuff underneath changes. That'll be tough to catch but should be caught in upstream testing anyway
